on:

permissions:
  contents: read
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: stone-payments/approved-actions/actions/checkout/v2@stable
      - name: Run ansible-lint
        uses: stone-payments/approved-actions/ansible/ansible-lint/main@stable
